import { useState, useEffect } from 'react';
import { Wallet, Eye, FileText, X, Filter, CheckCircle, Clock, TrendingUp, Settings, Loader2, Plus, AlertCircle, Database } from 'lucide-react';
import PageHeader from '../components/PageHeader.jsx';
import StatCard from '../components/StatCard.jsx';
import Button from '../components/ui/Button.jsx';
import Input from '../components/ui/Input.jsx';
import Select from '../components/ui/Select.jsx';
import Badge from '../components/ui/Badge.jsx';
import Modal from '../components/ui/Modal.jsx';
import { useToast } from '../components/Toast/ToastProvider.jsx';
import styles from './Funds.module.css';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';

const emptyForm = { 
  memberName: '', rollNo: '', department: 'BS-IT', semester: '1st', 
  timing: 'Morning', amount: '', status: '', receipt: null, receiptPreview: null 
};

const Funds = () => {
  const [fundList, setFundList] = useState([]);
  const [expenseList, setExpenseList] = useState([]); 
  const [societyStudents, setSocietyStudents] = useState([]); // 🔴 NEW: Tracks actual student debts
  const [monthlyFee, setMonthlyFee] = useState(500);

  const [dialogOpen, setDialogOpen] = useState(false);
  const [feeModalOpen, setFeeModalOpen] = useState(false);
  const [newFee, setNewFee] = useState('');
  
  const [form, setForm] = useState(emptyForm);
  const [previewReceipt, setPreviewReceipt] = useState(null);
  
  const [timeFilter, setTimeFilter] = useState('All'); 
  const [statusFilter, setStatusFilter] = useState('All'); 
  
  const [isLoading, setIsLoading] = useState(true);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const { toast } = useToast();

  useEffect(() => {
    const fetchData = async () => {
      // 🔴 ENTERPRISE FIX: Added required authorization headers to protect the President's routes
      const headers = { 'Authorization': `Bearer ${sessionStorage.getItem('token')}` };

      try {
        const [feeRes, fundsRes, expensesRes, studentsRes] = await Promise.all([
          fetch(`${API_URL}/settings/fee`, { headers }).catch(() => null),
          fetch(`${API_URL}/fund-collections/records`, { headers }).catch(() => null),
          fetch(`${API_URL}/expenses/records`, { headers }).catch(() => null),
          // Fetching all students to accurately cross-reference unpaid dues generated by CRs
          fetch(`${API_URL}/students/all`, { headers }).catch(() => null) 
        ]);

        if (feeRes && feeRes.ok) {
          const feeData = await feeRes.json();
          setMonthlyFee(feeData.fee);
          setNewFee(feeData.fee);
        }
        if (fundsRes && fundsRes.ok) setFundList(await fundsRes.json());
        if (expensesRes && expensesRes.ok) setExpenseList(await expensesRes.json());
        
        // Handle student data (fallback to /students if /students/all doesn't exist)
        if (studentsRes && studentsRes.ok) {
          setSocietyStudents(await studentsRes.json());
        } else {
          const altStuRes = await fetch(`${API_URL}/students`, { headers }).catch(() => null);
          if (altStuRes && altStuRes.ok) setSocietyStudents(await altStuRes.json());
        }

      } catch (error) {
        toast({ title: 'Connection Error', description: 'Failed to synchronize live treasury data.', variant: 'destructive' });
      } finally {
        setIsLoading(false);
      }
    };
    
    fetchData();
  }, [toast]);

  const setField = (k, v) => setForm(p => ({ ...p, [k]: v }));

  const handleUpdateFee = async () => {
    if (!newFee || newFee <= 0) {
      toast({ title: 'Invalid Amount', description: 'Enter a valid fee greater than 0.', variant: 'destructive' }); 
      return;
    }
    
    setIsSubmitting(true);
    try {
      const res = await fetch(`${API_URL}/settings/fee`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${sessionStorage.getItem('token')}` },
        body: JSON.stringify({ fee: newFee })
      });
      
      if (res.ok) {
        const data = await res.json();
        setMonthlyFee(data.fee);
        toast({ title: 'Success', description: 'Standard Monthly Fee updated globally.' });
        setFeeModalOpen(false);
      } else {
        throw new Error('Failed to update');
      }
    } catch (error) {
      toast({ title: 'Update Failed', description: 'Could not update the fee settings.', variant: 'destructive' });
    } finally {
      setIsSubmitting(false);
    }
  };

  const filterByTime = (list) => {
    if (timeFilter === 'All') return list;
    const today = new Date();
    return list.filter(record => {
      if (!record.date) return false;
      const recordDate = new Date(record.date);
      if (timeFilter === 'This Year') return recordDate.getFullYear() === today.getFullYear();
      if (timeFilter === 'This Month') return recordDate.getFullYear() === today.getFullYear() && recordDate.getMonth() === today.getMonth();
      if (timeFilter === 'This Week') {
        const startOfWeek = new Date(today);
        startOfWeek.setDate(today.getDate() - today.getDay());
        startOfWeek.setHours(0, 0, 0, 0);
        const endOfWeek = new Date(startOfWeek);
        endOfWeek.setDate(startOfWeek.getDate() + 6);
        endOfWeek.setHours(23, 59, 59, 999);
        return recordDate >= startOfWeek && recordDate <= endOfWeek;
      }
      return true;
    });
  };

  // 🔴 ENTERPRISE LOGIC: SEPARATING TRANSACTIONS FROM DEBTS
  const timeFilteredTransactions = filterByTime(fundList);
  const timeFilteredExpenses = filterByTime(expenseList); 

  const paidTransactions = timeFilteredTransactions.filter(f => f.status === 'Paid');
  const manualUnpaidTransactions = timeFilteredTransactions.filter(f => f.status !== 'Paid');
  
  // Create virtual "Debt" records dynamically from the Student database (Updated by CRs)
  const activeStudentDebts = societyStudents
    .filter(s => s.fundStatus === 'Unpaid' || s.fundStatus === 'Pending')
    .map(s => ({
      _id: `debt_${s._id}`,
      studentName: s.fullName,
      department: s.department,
      rollNo: s.rollNumber,
      semester: s.semester,
      timing: s.shift, 
      amount: monthlyFee + (s.arrears || 0),
      status: s.fundStatus, // 'Unpaid' or 'Pending'
      date: new Date().toISOString(), // Debts are current
      uploadedBy: 'CR Database Sync',
      isDebt: true
    }));

  // Combine manual unpaid entries + live student debts for the Master Ledger
  const combinedPendingAndUnpaid = [...manualUnpaidTransactions, ...activeStudentDebts];
  
  const totalCollected = paidTransactions.reduce((s, f) => s + (Number(f.amount) || 0), 0);
  const totalPendingAmount = combinedPendingAndUnpaid.reduce((s, f) => s + (Number(f.amount) || 0), 0);
  const totalExpected = totalCollected + totalPendingAmount;
  
  const totalExpenses = timeFilteredExpenses.reduce((s, e) => s + (Number(e.amount) || 0), 0);
  const availableBalance = totalCollected - totalExpenses;

  const paidCount = paidTransactions.length;
  const pendingCount = combinedPendingAndUnpaid.length;
  const totalCount = paidCount + pendingCount;

  // Master array for the table
  const allMasterRecords = [...paidTransactions, ...combinedPendingAndUnpaid];

  const displayFunds = allMasterRecords.filter(f => {
    if (statusFilter === 'All') return true;
    if (statusFilter === 'Pending/Unpaid') return f.status === 'Pending' || f.status === 'Unpaid';
    return f.status === statusFilter;
  });

  const handleFileChange = (e) => {
    const file = e.target.files[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (ev) => {
      setForm(p => ({ ...p, receipt: file, receiptPreview: ev.target.result }));
    };
    reader.readAsDataURL(file);
  };

  const handleSave = async () => {
    if (!form.memberName.trim() || !form.amount || !form.status) {
      toast({ title: 'Validation Error', description: 'Please fill all required fields', variant: 'destructive' }); 
      return;
    }

    setIsSubmitting(true);
    const newFund = {
      studentName: form.memberName.trim(),
      rollNo: form.rollNo.trim(), 
      department: form.department,
      semester: form.semester,
      timing: form.timing,
      amount: Number(form.amount),
      status: form.status,
      date: new Date().toISOString().split('T')[0],
      receiptName: form.receipt ? form.receipt.name : null,
      receiptData: form.receiptPreview || null,
      uploadedBy: 'President / Admin'
    };

    try {
      const res = await fetch(`${API_URL}/fund-collections/record`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${sessionStorage.getItem('token')}` },
        body: JSON.stringify(newFund)
      });

      if (res.ok) {
        const savedFund = await res.json();
        setFundList(prev => [savedFund, ...prev]);
        toast({ title: 'Success', description: 'Fund Record Added to the Master Ledger.' });
        setDialogOpen(false);
        setForm(emptyForm);
      } else {
        throw new Error('Failed to save');
      }
    } catch (error) {
      toast({ title: 'Server Error', description: 'Failed to add fund record.', variant: 'destructive' });
    } finally {
      setIsSubmitting(false);
    }
  };

  if (isLoading) {
    return (
      <div className={styles.loadingState}>
        <Loader2 className={styles.spin} size={48} />
        <h2>Syncing Treasury Data...</h2>
        <p>Gathering transactions and live class registries.</p>
      </div>
    );
  }

  return (
    <div className={styles.pageWrap}>
      <PageHeader 
        title="Fund Management" 
        description="Master ledger: Track payments, monitor class debts, and manage society funds." 
        actionLabel={<><Plus size={16} style={{marginRight: '6px'}}/> Add Fund Record</>} 
        onAction={() => { setForm(emptyForm); setDialogOpen(true); }} 
      />

      <div className={styles.controlsRow}>
        <div className={styles.timeFilters}>
          <Filter size={16} color="var(--text-muted)" style={{ marginRight: '4px' }} />
          {['All', 'This Week', 'This Month', 'This Year'].map(filterOption => (
            <Button 
              key={filterOption} 
              size="sm" 
              className={timeFilter === filterOption ? styles.btnActiveGreen : styles.btnOutlineGreen}
              onClick={() => { setTimeFilter(filterOption); setStatusFilter('All'); }}
            >
              {filterOption}
            </Button>
          ))}
        </div>
        
        <Button className={styles.btnOutlineGreen} onClick={() => setFeeModalOpen(true)}>
          <Settings size={16} style={{ marginRight: '8px' }}/> Set Monthly Fee (Rs {monthlyFee})
        </Button>
      </div>

      <p className={styles.hintText}>Click on a card below to filter the master ledger by payment status.</p>

      <div className={styles.statsGrid}>
        <div onClick={() => setStatusFilter('All')} className={`${styles.statWrapper} ${statusFilter === 'All' ? styles.statActive : styles.statInactive}`}>
          <StatCard title={`Total Expected (${timeFilter})`} value={`Rs ${totalExpected.toLocaleString()}`} icon={Wallet} description={`From ${totalCount} combined records`} />
        </div>
        <div onClick={() => setStatusFilter('Paid')} className={`${styles.statWrapper} ${statusFilter === 'Paid' ? styles.statActive : styles.statInactive}`}>
          <StatCard title={`Collected (${timeFilter})`} value={`Rs ${totalCollected.toLocaleString()}`} icon={CheckCircle} description={`${paidCount} successful transactions`} />
        </div>
        
        {/* 🔴 FIXED PENDING WIDGET: Accurately counts CR-generated debts */}
        <div onClick={() => setStatusFilter('Pending/Unpaid')} className={`${styles.statWrapper} ${statusFilter === 'Pending/Unpaid' ? styles.statActiveWarning : styles.statInactive}`}>
          <StatCard title={`Pending & Unpaid (${timeFilter})`} value={`Rs ${totalPendingAmount.toLocaleString()}`} icon={Clock} description={`${pendingCount} outstanding records`} />
        </div>
        
        <div className={styles.statWrapper}>
          <StatCard title={`Available Balance (${timeFilter})`} value={`Rs ${availableBalance.toLocaleString()}`} icon={TrendingUp} description={`Collected minus Rs ${totalExpenses.toLocaleString()} expenses`} />
        </div>
      </div>

      <div className={styles.tableHeaderRow}>
        <h3 className={styles.tableTitle}>
          {statusFilter === 'All' ? 'Master Ledger (All Records)' : statusFilter === 'Pending/Unpaid' ? 'Outstanding Debts & Pending' : `${statusFilter} Transactions`}
        </h3>
        {statusFilter !== 'All' && (
          <Button size="sm" variant="ghost" onClick={() => setStatusFilter('All')} className={styles.clearFilterBtn}>
            <X size={14} style={{ marginRight: '6px' }} /> Clear Filter
          </Button>
        )}
      </div>

      <div className={styles.tableWrap}>
        <table className={styles.table}>
          <thead>
            <tr>
              <th>Student Name</th>
              <th className={styles.hideSmall}>Department & Details</th>
              <th>Amount</th>
              <th>Status</th>
              <th className={styles.hideMd}>Date Recorded</th>
              <th>Data Source</th>
              <th>Receipt</th>
            </tr>
          </thead>
          <tbody>
            {displayFunds.length > 0 ? displayFunds.map(f => (
              <tr key={f._id} className={f.isDebt ? styles.rowDebt : ''}>
                <td className={styles.bold}>{f.studentName}</td>
                <td className={`${styles.hideSmall} ${styles.muted}`}>
                  <div className={styles.deptText}>{f.department || '—'} {f.rollNo ? `(${f.rollNo})` : ''}</div>
                  <div className={styles.subText}>{f.semester ? `${f.semester} Sem` : ''} {f.semester && f.timing ? '•' : ''} {f.timing || ''}</div>
                </td>
                <td className={styles.amountText} style={{ color: f.isDebt ? '#ef4444' : '#52a447' }}>
                  Rs {f.amount?.toLocaleString() || 0}
                </td>
                <td>
                  <Badge variant={f.status === 'Paid' ? 'success' : f.status === 'Pending' ? 'warning' : 'destructive'}>
                    {f.status === 'Pending' ? 'Pending (Arrears)' : f.status}
                  </Badge>
                </td>
                <td className={`${styles.hideMd} ${styles.muted}`}>
                  {f.isDebt ? <span className={styles.debtDate}><Clock size={12}/> Outstanding</span> : (f.date ? new Date(f.date).toLocaleDateString() : '—')}
                </td>
                <td>
                  {f.isDebt ? (
                     <span className={styles.sourceTag}><Database size={12}/> Sync</span>
                  ) : (
                     <Badge variant="outline">{f.uploadedBy || 'System'}</Badge>
                  )}
                </td>
                <td>
                  {f.receiptData ? (
                    <button className={styles.viewReceiptBtn} onClick={() => setPreviewReceipt(f)}>
                      <Eye size={14} /> View File
                    </button>
                  ) : f.receiptName ? (
                    <span className={styles.receiptFile}><FileText size={14} /> {f.receiptName}</span>
                  ) : f.status === 'Paid' ? (
                    <button className={styles.eReceiptBtn} onClick={() => setPreviewReceipt(f)}>
                      <CheckCircle size={14} /> E-Receipt
                    </button>
                  ) : (
                    <span className={styles.muted}>Awaiting Payment</span>
                  )}
                </td>
              </tr>
            )) : (
              <tr>
                <td colSpan={7} className={styles.emptyTable}>
                  <AlertCircle size={24} style={{marginBottom: '10px', color: '#cbd5e1'}} />
                  <br />
                  No {statusFilter === 'Pending/Unpaid' ? 'pending or unpaid' : statusFilter.toLowerCase()} fund records found for {timeFilter.toLowerCase()}.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      {/* RECEIPT MODAL */}
      {previewReceipt && (
        <div className={styles.receiptOverlay} onClick={() => setPreviewReceipt(null)}>
          <div className={styles.receiptModal} onClick={e => e.stopPropagation()}>
            <div className={styles.receiptHeader}>
              <div>
                <h3 className={styles.receiptTitle}>Payment Receipt</h3>
                <p className={styles.receiptSub}>{previewReceipt.studentName} • Rs {previewReceipt.amount?.toLocaleString() || 0} • {new Date(previewReceipt.date).toLocaleDateString()}</p>
              </div>
              <button className={styles.receiptClose} onClick={() => setPreviewReceipt(null)}><X size={18} /></button>
            </div>
            <div className={styles.receiptBody}>
              {previewReceipt.receiptData?.startsWith('data:image') ? (
                <img src={previewReceipt.receiptData} alt="Receipt" className={styles.receiptImg} />
              ) : previewReceipt.receiptData?.startsWith('data:application/pdf') ? (
                <iframe src={previewReceipt.receiptData} className={styles.receiptPdf} title="Receipt PDF" />
              ) : (
                <div className={styles.eReceiptContainer}>
                  <div className={styles.eReceiptIconWrap}>
                    <CheckCircle size={36} color="#52a447" />
                  </div>
                  <h2 className={styles.eReceiptHeading}>Official E-Receipt</h2>
                  <div className={styles.eReceiptCard}>
                    <div className={styles.eReceiptRow}><span>Student Name</span><strong>{previewReceipt.studentName}</strong></div>
                    <div className={styles.eReceiptRow}><span>Department</span><strong>{previewReceipt.department}</strong></div>
                    <div className={styles.eReceiptRow}><span>Amount Paid</span><strong className={styles.eReceiptAmount}>Rs {previewReceipt.amount?.toLocaleString()}</strong></div>
                    <div className={styles.eReceiptRow}><span>Collected By</span><strong>{previewReceipt.uploadedBy}</strong></div>
                    <div className={styles.eReceiptRow} style={{borderBottom: 'none', paddingBottom: 0}}><span>Date</span><strong>{new Date(previewReceipt.date).toLocaleDateString()}</strong></div>
                  </div>
                  <p className={styles.eReceiptDisclaimer}>This is a system-generated electronic receipt.<br/>No physical signature is required.</p>
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {/* FEE MODAL */}
      <Modal open={feeModalOpen} onClose={() => !isSubmitting && setFeeModalOpen(false)} title="Set Standard Monthly Fee" 
        footer={
          <div style={{display: 'flex', gap: '8px', justifyContent: 'flex-end', width: '100%'}}>
            <Button variant="outline" onClick={() => setFeeModalOpen(false)} disabled={isSubmitting}>Cancel</Button>
            <Button onClick={handleUpdateFee} disabled={isSubmitting} style={{backgroundColor: '#52a447'}}>
              {isSubmitting ? <><Loader2 size={16} className={styles.spin} style={{marginRight: '6px'}}/> Saving...</> : 'Save Fee'}
            </Button>
          </div>
        }>
        <div className={styles.formFields}>
          <div className={styles.field}>
            <label>Amount (Rs) <span style={{color: 'red'}}>*</span></label>
            <Input type="number" value={newFee} onChange={e => setNewFee(e.target.value)} disabled={isSubmitting} />
          </div>
          <p style={{ fontSize: '0.85rem', color: '#64748b', lineHeight: 1.5 }}>This base amount will be automatically applied and suggested on all Class Representatives' dashboards.</p>
        </div>
      </Modal>

      {/* ADD FUND MODAL */}
      <Modal open={dialogOpen} onClose={() => !isSubmitting && setDialogOpen(false)} title="Add Direct Fund Record" 
        footer={
          <div style={{display: 'flex', gap: '8px', justifyContent: 'flex-end', width: '100%'}}>
            <Button variant="outline" onClick={() => setDialogOpen(false)} disabled={isSubmitting}>Cancel</Button>
            <Button onClick={handleSave} disabled={isSubmitting} style={{backgroundColor: '#52a447'}}>
               {isSubmitting ? <><Loader2 size={16} className={styles.spin} style={{marginRight: '6px'}}/> Saving...</> : 'Save Record'}
            </Button>
          </div>
        }>
        <div className={styles.formFields}>
          <div className={styles.field}>
            <label>Student Name <span style={{color: 'red'}}>*</span></label>
            <Input placeholder="Enter student name" value={form.memberName} onChange={e => setField('memberName', e.target.value)} disabled={isSubmitting} />
          </div>
          <div style={{ display: 'flex', gap: '16px' }}>
            <div className={styles.field} style={{ flex: 1 }}>
              <label>Department <span style={{color: 'red'}}>*</span></label>
              <Select value={form.department} onChange={e => setField('department', e.target.value)} disabled={isSubmitting}>
                <option value="BS-IT">BS-IT</option><option value="Computer Science">Computer Science</option><option value="Software Engineering">Software Engineering</option><option value="Economics">Economics</option><option value="Maths">Maths</option>
              </Select>
            </div>
            <div className={styles.field} style={{ flex: 1 }}>
              <label>Roll Number</label>
              <Input value={form.rollNo} onChange={e => setField('rollNo', e.target.value)} placeholder="e.g. 22034156-043" disabled={isSubmitting} />
            </div>
          </div>
          <div style={{ display: 'flex', gap: '16px' }}>
            <div className={styles.field} style={{ flex: 1 }}>
              <label>Semester <span style={{color: 'red'}}>*</span></label>
              <Select value={form.semester} onChange={e => setField('semester', e.target.value)} disabled={isSubmitting}>
                {['1st','2nd','3rd','4th','5th','6th','7th','8th'].map(s => <option key={s} value={s}>{s} Semester</option>)}
              </Select>
            </div>
            <div className={styles.field} style={{ flex: 1 }}>
              <label>Timing <span style={{color: 'red'}}>*</span></label>
              <Select value={form.timing} onChange={e => setField('timing', e.target.value)} disabled={isSubmitting}>
                <option value="Morning">Morning</option><option value="Evening">Evening</option>
              </Select>
            </div>
          </div>
          <div className={styles.field}>
            <label>Amount (Rs) <span style={{color: 'red'}}>*</span></label>
            <Input type="number" placeholder="e.g. 500" value={form.amount} onChange={e => setField('amount', e.target.value)} disabled={isSubmitting} />
          </div>
          <div className={styles.field}>
            <label>Payment Status <span style={{color: 'red'}}>*</span></label>
            <Select value={form.status} onChange={e => setField('status', e.target.value)} disabled={isSubmitting}>
              <option value="">Select Status</option>
              <option value="Paid">Paid</option>
              <option value="Pending">Pending (Partial Payment / Arrears)</option>
              <option value="Unpaid">Unpaid</option>
            </Select>
          </div>
          <div className={styles.field}>
            <label>Upload Manual Receipt (Optional)</label>
            <div className={styles.uploadWrap}>
              <input type="file" accept="image/*,.pdf" id="receiptUpload" className={styles.fileInput} onChange={handleFileChange} disabled={isSubmitting} />
              <label htmlFor="receiptUpload" className={`${styles.uploadBtn} ${isSubmitting ? styles.disabled : ''}`}>
                {form.receipt ? form.receipt.name : 'Choose file...'}
              </label>
              {form.receiptPreview && form.receiptPreview.startsWith('data:image') && <img src={form.receiptPreview} alt="Preview" className={styles.uploadPreview} />}
            </div>
          </div>
        </div>
      </Modal>
    </div>
  );
};

export default Funds;